# Generated by Django 6.0.7 on 2026-08-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
    ]
